

      var mic = new Wit.Microphone(document.getElementById("microphone"));
      var info = function (msg) {
        document.getElementById("info").innerHTML = msg;
      };
      var error = function (msg) {
        document.getElementById("error").innerHTML = msg;
      };
      mic.onready = function () {
        info("Microphone is ready to record");
      };
      mic.onaudiostart = function () {
        info("Recording started");
        error("");
      };
      mic.onaudioend = function () {
        info("Recording stopped, processing started");
      };
      mic.onresult = function (intent, entities) {
	var out_text = "That does not make sense."
	if (intent == "start") {
		out_text = "You can say things like\nGo to admin\nor\n what is a tiger";
	}
	if (intent == "dictionary") {
		var dict_site = "https://en.wiktionary.org/wiki/"
		window.location.href = dict_site + entities.wikipedia_search_query.value;
	}
	if (intent == "translate") {
		var translate_site = "https://translate.google.com/#en/";
		window.location.href = translate_site + lang[entities.message_subject.value] + '/' + entities.message_body.value;
	}
	if (intent == "wikipedia") {
		var msg = entities.wikipedia_search_query.value
		msg = msg.split(' ').join('_');
		var wiki_page = "http://en.wikipedia.org/wiki/"
		$.ajax({
    			type: 'GET',
    			url: "proxy2.php?url=" + wiki_page + msg,
			success: function(data) {
				if (data == '') {	
					var search_url = "http%3A%2F%2Fen.wikipedia.org%2Fw%2Fapi.php%3Faction%3Dopensearch%26search%3D" + msg
                                	$.ajax({
                                	        type: 'GET',
                                	        url: "proxy2.php?url=" + search_url,
						dataType: "json",
                                	        success: function(data) {
							window.location.href = wiki_page + data[1][0]
                                	        },
						error: function() { alert("ERROR");}
                                	});
				}
				else if (data != '') {
 					window.location.href = wiki_page + msg;
				}
			}
		});
		out_text = JSON.stringify(msg)
	}
	if (intent == "go") {
		msg = entities.message_body.body
		if (msg == "administrator") {
			window.location.replace("/fish_lights/admin");
		}
		if (msg == "fish lights" || msg == "fish lite") {
			window.location.replace("/fish_lights");
		}
		if (msg == "home") {
			window.location.replace("/home");
		}
		out_text = JSON.stringify(msg);
	}
        $('.result').updateWithText(out_text, 1000)
      };
      mic.onerror = function (err) {
        error("Error: " + err);
      };
      mic.onconnecting = function () {
        info("Microphone is connecting");
      };
      mic.ondisconnected = function () {
        info("Microphone is not connected");
      };

      mic.connect("A6G5I4WDT4Z54COVGYVXO3YXOD63C2OQ");
      // mic.start();
      // mic.stop();

      function kv (k, v) {
        if (toString.call(v) !== "[object String]") {
          v = JSON.stringify(v);
        }
        return k + "=" + v + "\n";
      }

$.fn.updateWithText = function(text, speed)
{
	var dummy = $('<div/>').html(text);

	if ($(this).html() != dummy.html())
	{
		$(this).fadeOut(speed/2, function() {
			$(this).html(text);
			$(this).fadeIn(speed/2, function() {
				//done
			});
		});
	}
}

var lang = new Array();
lang["Afar"] = "aa"
lang["Abkhazian"] = "ab"
lang["Achinese"] = ""
lang["Acoli"] = ""
lang["Adangme"] = ""
lang["Adyghe; Adygei"] = ""
lang["Afro-Asiatic languages"] = ""
lang["Afrihili"] = ""
lang["Afrikaans"] = "af"
lang["Ainu"] = ""
lang["Akan"] = "ak"
lang["Akkadian"] = ""
lang["Albanian"] = "sq"
lang["Aleut"] = ""
lang["Algonquian languages"] = ""
lang["Southern Altai"] = ""
lang["Amharic"] = "am"
lang["Angika"] = ""
lang["Apache languages"] = ""
lang["Arabic"] = "ar"
lang["Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"] = ""
lang["Aragonese"] = "an"
lang["Armenian"] = "hy"
lang["Mapudungun; Mapuche"] = ""
lang["Arapaho"] = ""
lang["Artificial languages"] = ""
lang["Arawak"] = ""
lang["Assamese"] = "as"
lang["Asturian; Bable; Leonese; Asturleonese"] = ""
lang["Athapascan languages"] = ""
lang["Australian languages"] = ""
lang["Avaric"] = "av"
lang["Avestan"] = "ae"
lang["Awadhi"] = ""
lang["Aymara"] = "ay"
lang["Azerbaijani"] = "az"
lang["Banda languages"] = ""
lang["Bamileke languages"] = ""
lang["Bashkir"] = "ba"
lang["Baluchi"] = ""
lang["Bambara"] = "bm"
lang["Balinese"] = ""
lang["Basque"] = "eu"
lang["Basa"] = ""
lang["Baltic languages"] = ""
lang["Beja; Bedawiyet"] = ""
lang["Belarusian"] = "be"
lang["Bemba"] = ""
lang["Bengali"] = "bn"
lang["Berber languages"] = ""
lang["Bhojpuri"] = ""
lang["Bihari languages"] = "bh"
lang["Bikol"] = ""
lang["Bini; Edo"] = ""
lang["Bislama"] = "bi"
lang["Siksika"] = ""
lang["Bantu (Other)"] = ""
lang["Bosnian"] = "bs"
lang["Braj"] = ""
lang["Breton"] = "br"
lang["Batak languages"] = ""
lang["Buriat"] = ""
lang["Buginese"] = ""
lang["Bulgarian"] = "bg"
lang["Burmese"] = "my"
lang["Blin; Bilin"] = ""
lang["Caddo"] = ""
lang["Central American Indian languages"] = ""
lang["Galibi Carib"] = ""
lang["Catalan; Valencian"] = "ca"
lang["Caucasian languages"] = ""
lang["Cebuano"] = ""
lang["Celtic languages"] = ""
lang["Chamorro"] = "ch"
lang["Chibcha"] = ""
lang["Chechen"] = "ce"
lang["Chagatai"] = ""
lang["Chinese"] = "zh"
lang["Chuukese"] = ""
lang["Mari"] = ""
lang["Chinook jargon"] = ""
lang["Choctaw"] = ""
lang["Chipewyan; Dene Suline"] = ""
lang["Cherokee"] = ""
lang["Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"] = "cu"
lang["Chuvash"] = "cv"
lang["Cheyenne"] = ""
lang["Chamic languages"] = ""
lang["Coptic"] = ""
lang["Cornish"] = "kw"
lang["Corsican"] = "co"
lang["Cree"] = "cr"
lang["Crimean Tatar; Crimean Turkish"] = ""
lang["Creoles and pidgins "] = ""
lang["Kashubian"] = ""
lang["Cushitic languages"] = ""
lang["Czech"] = "cs"
lang["Dakota"] = ""
lang["Danish"] = "da"
lang["Dargwa"] = ""
lang["Land Dayak languages"] = ""
lang["Delaware"] = ""
lang["Slave (Athapascan)"] = ""
lang["Dogrib"] = ""
lang["Dinka"] = ""
lang["Divehi; Dhivehi; Maldivian"] = "dv"
lang["Dogri"] = ""
lang["Dravidian languages"] = ""
lang["Lower Sorbian"] = ""
lang["Duala"] = ""
lang["Dutch; Flemish"] = "nl"
lang["Dyula"] = ""
lang["Dzongkha"] = "dz"
lang["Efik"] = ""
lang["Egyptian (Ancient)"] = ""
lang["Ekajuk"] = ""
lang["Elamite"] = ""
lang["English"] = "en"
lang["Esperanto"] = "eo"
lang["Estonian"] = "et"
lang["Ewe"] = "ee"
lang["Ewondo"] = ""
lang["Fang"] = ""
lang["Faroese"] = "fo"
lang["Fanti"] = ""
lang["Fijian"] = "fj"
lang["Filipino; Pilipino"] = ""
lang["Finnish"] = "fi"
lang["Finno-Ugrian languages"] = ""
lang["Fon"] = ""
lang["French"] = "fr"
lang["Northern Frisian"] = ""
lang["Eastern Frisian"] = ""
lang["Western Frisian"] = "fy"
lang["Fulah"] = "ff"
lang["Friulian"] = ""
lang["Ga"] = ""
lang["Gayo"] = ""
lang["Gbaya"] = ""
lang["Germanic languages"] = ""
lang["Georgian"] = "ka"
lang["German"] = "de"
lang["Geez"] = ""
lang["Gilbertese"] = ""
lang["Gaelic"] = "gd"
lang["Irish"] = "ga"
lang["Galician"] = "gl"
lang["Manx"] = "gv"
lang["Gondi"] = ""
lang["Gorontalo"] = ""
lang["Gothic"] = ""
lang["Grebo"] = ""
lang["Greek"] = "el"
lang["Guarani"] = "gn"
lang["Swiss German; Alemannic; Alsatian"] = ""
lang["Gujarati"] = "gu"
lang["Gwich'in"] = ""
lang["Haida"] = ""
lang["Haitian; Haitian Creole"] = "ht"
lang["Hausa"] = "ha"
lang["Hawaiian"] = ""
lang["Hebrew"] = "he"
lang["Herero"] = "hz"
lang["Hiligaynon"] = ""
lang["Himachali languages; Western Pahari languages"] = ""
lang["Hindi"] = "hi"
lang["Hittite"] = ""
lang["Hmong; Mong"] = ""
lang["Hiri Motu"] = "ho"
lang["Croatian"] = "hr"
lang["Upper Sorbian"] = ""
lang["Hungarian"] = "hu"
lang["Hupa"] = ""
lang["Iban"] = ""
lang["Igbo"] = "ig"
lang["Icelandic"] = "is"
lang["Ido"] = "io"
lang["Sichuan Yi; Nuosu"] = "ii"
lang["Ijo languages"] = ""
lang["Inuktitut"] = "iu"
lang["Interlingue; Occidental"] = "ie"
lang["Iloko"] = ""
lang["Interlingua (International Auxiliary Language Association)"] = "ia"
lang["Indic languages"] = ""
lang["Indonesian"] = "id"
lang["Indo-European languages"] = ""
lang["Ingush"] = ""
lang["Inupiaq"] = "ik"
lang["Iranian languages"] = ""
lang["Iroquoian languages"] = ""
lang["Italian"] = "it"
lang["Javanese"] = "jv"
lang["Lojban"] = ""
lang["Japanese"] = "ja"
lang["Judeo-Persian"] = ""
lang["Judeo-Arabic"] = ""
lang["Kara-Kalpak"] = ""
lang["Kabyle"] = ""
lang["Kachin; Jingpho"] = ""
lang["Kalaallisut; Greenlandic"] = "kl"
lang["Kamba"] = ""
lang["Kannada"] = "kn"
lang["Karen languages"] = ""
lang["Kashmiri"] = "ks"
lang["Kanuri"] = "kr"
lang["Kawi"] = ""
lang["Kazakh"] = "kk"
lang["Kabardian"] = ""
lang["Khasi"] = ""
lang["Khoisan languages"] = ""
lang["Central Khmer"] = "km"
lang["Khotanese; Sakan"] = ""
lang["Kikuyu; Gikuyu"] = "ki"
lang["Kinyarwanda"] = "rw"
lang["Kirghiz; Kyrgyz"] = "ky"
lang["Kimbundu"] = ""
lang["Konkani"] = ""
lang["Komi"] = "kv"
lang["Kongo"] = "kg"
lang["Korean"] = "ko"
lang["Kosraean"] = ""
lang["Kpelle"] = ""
lang["Karachay-Balkar"] = ""
lang["Karelian"] = ""
lang["Kru languages"] = ""
lang["Kurukh"] = ""
lang["Kuanyama; Kwanyama"] = "kj"
lang["Kumyk"] = ""
lang["Kurdish"] = "ku"
lang["Kutenai"] = ""
lang["Ladino"] = ""
lang["Lahnda"] = ""
lang["Lamba"] = ""
lang["Lao"] = "lo"
lang["Latin"] = "la"
lang["Latvian"] = "lv"
lang["Lezghian"] = ""
lang["Limburgan; Limburger; Limburgish"] = "li"
lang["Lingala"] = "ln"
lang["Lithuanian"] = "lt"
lang["Mongo"] = ""
lang["Lozi"] = ""
lang["Luxembourgish; Letzeburgesch"] = "lb"
lang["Luba-Lulua"] = ""
lang["Luba-Katanga"] = "lu"
lang["Ganda"] = "lg"
lang["Luiseno"] = ""
lang["Lunda"] = ""
lang["Luo (Kenya and Tanzania)"] = ""
lang["Lushai"] = ""
lang["Macedonian"] = "mk"
lang["Madurese"] = ""
lang["Magahi"] = ""
lang["Marshallese"] = "mh"
lang["Maithili"] = ""
lang["Makasar"] = ""
lang["Malayalam"] = "ml"
lang["Mandingo"] = ""
lang["Maori"] = "mi"
lang["Austronesian languages"] = ""
lang["Marathi"] = "mr"
lang["Masai"] = ""
lang["Malay"] = "ms"
lang["Moksha"] = ""
lang["Mandar"] = ""
lang["Mi'kmaq; Micmac"] = ""
lang["Minangkabau"] = ""
lang["Uncoded languages"] = ""
lang["Mon-Khmer languages"] = ""
lang["Malagasy"] = "mg"
lang["Maltese"] = "mt"
lang["Manchu"] = ""
lang["Manipuri"] = ""
lang["Manobo languages"] = ""
lang["Mohawk"] = ""
lang["Mongolian"] = "mn"
lang["Mossi"] = ""
lang["Multiple languages"] = ""
lang["Munda languages"] = ""
lang["Creek"] = ""
lang["Mirandese"] = ""
lang["Marwari"] = ""
lang["Mayan languages"] = ""
lang["Erzya"] = ""
lang["Nahuatl languages"] = ""
lang["North American Indian languages"] = ""
lang["Neapolitan"] = ""
lang["Nauru"] = "na"
lang["Navajo"] = "nv"
lang["Ndonga"] = "ng"
lang["Nepali"] = "ne"
lang["Nepal Bhasa; Newari"] = ""
lang["Nias"] = ""
lang["Niger-Kordofanian languages"] = ""
lang["Niuean"] = ""
lang["Norwegian"] = "nn"
lang["Nogai"] = ""
lang["Norwegian"] = "no"
lang["N'Ko"] = ""
lang["Pedi; Sepedi; Northern Sotho"] = ""
lang["Nubian languages"] = ""
lang["Classical Newari; Old Newari; Classical Nepal Bhasa"] = ""
lang["Chichewa; Chewa; Nyanja"] = "ny"
lang["Nyamwezi"] = ""
lang["Nyankole"] = ""
lang["Nyoro"] = ""
lang["Nzima"] = ""
lang["Occitan (post 1500); ProvenÃ§al"] = "oc"
lang["Ojibwa"] = "oj"
lang["Oriya"] = "or"
lang["Oromo"] = "om"
lang["Osage"] = ""
lang["Ossetian; Ossetic"] = "os"
lang["Turkish, Ottoman (1500-1928)"] = ""
lang["Otomian languages"] = ""
lang["Papuan languages"] = ""
lang["Pangasinan"] = ""
lang["Pahlavi"] = ""
lang["Pampanga; Kapampangan"] = ""
lang["Panjabi; Punjabi"] = "pa"
lang["Papiamento"] = ""
lang["Palauan"] = ""
lang["Persian"] = "fa"
lang["Philippine languages"] = ""
lang["Phoenician"] = ""
lang["Pali"] = "pi"
lang["Polish"] = "pl"
lang["Pohnpeian"] = ""
lang["Portuguese"] = "pt"
lang["Prakrit languages"] = ""
lang["Pushto; Pashto"] = "ps"
lang["Reserved for local use"] = ""
lang["Quechua"] = "qu"
lang["Rajasthani"] = ""
lang["Rapanui"] = ""
lang["Rarotongan; Cook Islands Maori"] = ""
lang["Romance languages"] = ""
lang["Romansh"] = "rm"
lang["Romany"] = ""
lang["Romanian; Moldavian; Moldovan"] = "ro"
lang["Rundi"] = "rn"
lang["Aromanian; Arumanian; Macedo-Romanian"] = ""
lang["Russian"] = "ru"
lang["Sandawe"] = ""
lang["Sango"] = "sg"
lang["Yakut"] = ""
lang["South American Indian (Other)"] = ""
lang["Salishan languages"] = ""
lang["Samaritan Aramaic"] = ""
lang["Sanskrit"] = "sa"
lang["Sasak"] = ""
lang["Santali"] = ""
lang["Sicilian"] = ""
lang["Scots"] = ""
lang["Selkup"] = ""
lang["Semitic languages"] = ""
lang["Sign Languages"] = ""
lang["Shan"] = ""
lang["Sidamo"] = ""
lang["Sinhala; Sinhalese"] = "si"
lang["Siouan languages"] = ""
lang["Sino-Tibetan languages"] = ""
lang["Slavic languages"] = ""
lang["Slovak"] = "sk"
lang["Slovenian"] = "sl"
lang["Southern Sami"] = ""
lang["Northern Sami"] = "se"
lang["Sami languages"] = ""
lang["Lule Sami"] = ""
lang["Inari Sami"] = ""
lang["Samoan"] = "sm"
lang["Skolt Sami"] = ""
lang["Shona"] = "sn"
lang["Sindhi"] = "sd"
lang["Soninke"] = ""
lang["Sogdian"] = ""
lang["Somali"] = "so"
lang["Songhai languages"] = ""
lang["Sotho"] = "st"
lang["Spanish; Castilian"] = "es"
lang["Sardinian"] = "sc"
lang["Sranan Tongo"] = ""
lang["Serbian"] = "sr"
lang["Serer"] = ""
lang["Nilo-Saharan languages"] = ""
lang["Swati"] = "ss"
lang["Sukuma"] = ""
lang["Sundanese"] = "su"
lang["Susu"] = ""
lang["Sumerian"] = ""
lang["Swahili"] = "sw"
lang["Swedish"] = "sv"
lang["Classical Syriac"] = ""
lang["Syriac"] = ""
lang["Tahitian"] = "ty"
lang["Tai languages"] = ""
lang["Tamil"] = "ta"
lang["Tatar"] = "tt"
lang["Telugu"] = "te"
lang["Timne"] = ""
lang["Tereno"] = ""
lang["Tetum"] = ""
lang["Tajik"] = "tg"
lang["Tagalog"] = "tl"
lang["Thai"] = "th"
lang["Tibetan"] = "bo"
lang["Tigre"] = ""
lang["Tigrinya"] = "ti"
lang["Tiv"] = ""
lang["Tokelau"] = ""
lang["Klingon; tlhIngan-Hol"] = ""
lang["Tlingit"] = ""
lang["Tamashek"] = ""
lang["Tonga (Nyasa)"] = ""
lang["Tonga (Tonga Islands)"] = "to"
lang["Tok Pisin"] = ""
lang["Tsimshian"] = ""
lang["Tswana"] = "tn"
lang["Tsonga"] = "ts"
lang["Turkmen"] = "tk"
lang["Tumbuka"] = ""
lang["Tupi languages"] = ""
lang["Turkish"] = "tr"
lang["Altaic languages"] = ""
lang["Tuvalu"] = ""
lang["Twi"] = "tw"
lang["Tuvinian"] = ""
lang["Udmurt"] = ""
lang["Ugaritic"] = ""
lang["Uighur; Uyghur"] = "ug"
lang["Ukrainian"] = "uk"
lang["Umbundu"] = ""
lang["Undetermined"] = ""
lang["Urdu"] = "ur"
lang["Uzbek"] = "uz"
lang["Vai"] = ""
lang["Venda"] = "ve"
lang["Vietnamese"] = "vi"
lang["VolapÃ_k"] = "vo"
lang["Votic"] = ""
lang["Wakashan languages"] = ""
lang["Walamo"] = ""
lang["Waray"] = ""
lang["Washo"] = ""
lang["Welsh"] = "cy"
lang["Sorbian languages"] = ""
lang["Walloon"] = "wa"
lang["Wolof"] = "wo"
lang["Kalmyk; Oirat"] = ""
lang["Xhosa"] = "xh"
lang["Yao"] = ""
lang["Yapese"] = ""
lang["Yiddish"] = "yi"
lang["Yoruba"] = "yo"
lang["Yupik languages"] = ""
lang["Zapotec"] = ""
lang["Blissymbols; Blissymbolics; Bliss"] = ""
lang["Zenaga"] = ""
lang["Standard Moroccan Tamazight"] = ""
lang["Zhuang; Chuang"] = "za"
lang["Zulu"] = "zu"
